from baml_client.async_client import types


CAR_DATABASE: list[types.CarInfo] = [
    types.CarInfo(
        make="Toyota",
        model="Camry",
        year=2023,
        type="sedan",
        sale_type="both",
        price=55,
        price_unit="usd_per_day",
        fuel_efficiency=32,
        features=["automatic", "AC", "Bluetooth", "lane assist"],
        horsepower=203,
        seats=5,
    ),
    types.CarInfo(
        make="Honda",
        model="Accord",
        year=2023,
        type="sedan",
        sale_type="both",
        price=58,
        price_unit="usd_per_day",
        fuel_efficiency=33,
        features=["automatic", "AC", "Apple CarPlay", "adaptive cruise"],
        horsepower=192,
        seats=5,
    ),
    types.CarInfo(
        make="Hyundai",
        model="Elantra",
        year=2022,
        type="sedan",
        sale_type="rental",
        price=48,
        price_unit="usd_per_day",
        fuel_efficiency=35,
        features=["automatic", "Bluetooth", "backup camera"],
        horsepower=147,
        seats=5,
    ),
    types.CarInfo(
        make="Nissan",
        model="Altima",
        year=2022,
        type="sedan",
        sale_type="both",
        price=52,
        price_unit="usd_per_day",
        fuel_efficiency=32,
        features=["automatic", "AC", "lane assist"],
        horsepower=188,
        seats=5,
    ),
    types.CarInfo(
        make="Mazda",
        model="Mazda3",
        year=2023,
        type="sedan",
        sale_type="sale",
        price=23000,
        price_unit="usd",
        fuel_efficiency=31,
        features=["sport mode", "premium sound"],
        horsepower=186,
        seats=5,
    ),
    types.CarInfo(
        make="BMW",
        model="330i",
        year=2024,
        type="luxury",
        sale_type="sale",
        price=46000,
        price_unit="usd",
        fuel_efficiency=30,
        features=["leather", "navigation", "sport package"],
        horsepower=255,
        seats=5,
    ),
    types.CarInfo(
        make="Mercedes",
        model="C300",
        year=2024,
        type="luxury",
        sale_type="sale",
        price=51000,
        price_unit="usd",
        fuel_efficiency=29,
        features=["sunroof", "premium sound"],
        horsepower=255,
        seats=5,
    ),
    types.CarInfo(
        make="Audi",
        model="A4",
        year=2023,
        type="luxury",
        sale_type="rental",
        price=120,
        price_unit="usd_per_day",
        fuel_efficiency=28,
        features=["quattro", "navigation"],
        horsepower=201,
        seats=5,
    ),
    types.CarInfo(
        make="Kia",
        model="K5",
        year=2023,
        type="sedan",
        sale_type="both",
        price=49,
        price_unit="usd_per_day",
        fuel_efficiency=32,
        features=["AC", "Bluetooth", "lane assist"],
        horsepower=180,
        seats=5,
    ),
    types.CarInfo(
        make="Volkswagen",
        model="Jetta",
        year=2022,
        type="sedan",
        sale_type="rental",
        price=46,
        price_unit="usd_per_day",
        fuel_efficiency=34,
        features=["automatic", "CarPlay"],
        horsepower=158,
        seats=5,
    ),
    # SUVs
    types.CarInfo(
        make="Toyota",
        model="RAV4",
        year=2023,
        type="suv",
        sale_type="both",
        price=72,
        price_unit="usd_per_day",
        fuel_efficiency=28,
        features=["AWD", "AC", "roof rack", "lane assist"],
        horsepower=203,
        seats=5,
    ),
    types.CarInfo(
        make="Honda",
        model="CR-V",
        year=2023,
        type="suv",
        sale_type="both",
        price=75,
        price_unit="usd_per_day",
        fuel_efficiency=29,
        features=["AWD", "Bluetooth", "CarPlay"],
        horsepower=190,
        seats=5,
    ),
    types.CarInfo(
        make="Ford",
        model="Escape",
        year=2022,
        type="suv",
        sale_type="rental",
        price=70,
        price_unit="usd_per_day",
        fuel_efficiency=27,
        features=["AWD", "backup camera"],
        horsepower=181,
        seats=5,
    ),
    types.CarInfo(
        make="Nissan",
        model="Rogue",
        year=2023,
        type="suv",
        sale_type="rental",
        price=68,
        price_unit="usd_per_day",
        fuel_efficiency=28,
        features=["AC", "lane assist"],
        horsepower=181,
        seats=5,
    ),
    types.CarInfo(
        make="Mazda",
        model="CX-5",
        year=2024,
        type="suv",
        sale_type="both",
        price=78,
        price_unit="usd_per_day",
        fuel_efficiency=26,
        features=["AWD", "premium interior"],
        horsepower=187,
        seats=5,
    ),
    # Trucks
    types.CarInfo(
        make="Ford",
        model="F-150",
        year=2023,
        type="truck",
        sale_type="sale",
        price=41000,
        price_unit="usd",
        fuel_efficiency=20,
        features=["4WD", "tow hitch"],
        horsepower=290,
        seats=5,
    ),
    types.CarInfo(
        make="Chevrolet",
        model="Silverado",
        year=2023,
        type="truck",
        sale_type="both",
        price=95,
        price_unit="usd_per_day",
        fuel_efficiency=19,
        features=["4WD", "bed liner"],
        horsepower=355,
        seats=5,
    ),
    types.CarInfo(
        make="Ram",
        model="1500",
        year=2023,
        type="truck",
        sale_type="rental",
        price=98,
        price_unit="usd_per_day",
        fuel_efficiency=20,
        features=["4WD", "AC"],
        horsepower=305,
        seats=5,
    ),
    types.CarInfo(
        make="Toyota",
        model="Tundra",
        year=2024,
        type="truck",
        sale_type="sale",
        price=48000,
        price_unit="usd",
        fuel_efficiency=19,
        features=["4WD", "premium interior"],
        horsepower=389,
        seats=5,
    ),
    types.CarInfo(
        make="Nissan",
        model="Frontier",
        year=2023,
        type="truck",
        sale_type="rental",
        price=82,
        price_unit="usd_per_day",
        fuel_efficiency=21,
        features=["AC", "Bluetooth"],
        horsepower=310,
        seats=5,
    ),
    types.CarInfo(
        make="GMC",
        model="Sierra",
        year=2023,
        type="truck",
        sale_type="sale",
        price=46000,
        price_unit="usd",
        fuel_efficiency=20,
        features=["4WD", "tow package"],
        horsepower=355,
        seats=5,
    ),
    types.CarInfo(
        make="Honda",
        model="Ridgeline",
        year=2023,
        type="truck",
        sale_type="both",
        price=110,
        price_unit="usd_per_day",
        fuel_efficiency=21,
        features=["AWD", "lockable bed trunk"],
        horsepower=280,
        seats=5,
    ),
    types.CarInfo(
        make="Ford",
        model="Ranger",
        year=2023,
        type="truck",
        sale_type="rental",
        price=88,
        price_unit="usd_per_day",
        fuel_efficiency=23,
        features=["4WD", "AC"],
        horsepower=270,
        seats=5,
    ),
    types.CarInfo(
        make="Chevrolet",
        model="Colorado",
        year=2023,
        type="truck",
        sale_type="sale",
        price=37000,
        price_unit="usd",
        fuel_efficiency=22,
        features=["4WD", "Bluetooth"],
        horsepower=237,
        seats=4,
    ),
    types.CarInfo(
        make="Toyota",
        model="Tacoma",
        year=2023,
        type="truck",
        sale_type="both",
        price=92,
        price_unit="usd_per_day",
        fuel_efficiency=21,
        features=["4WD", "premium sound"],
        horsepower=278,
        seats=5,
    ),
    # Electric (continued)
    types.CarInfo(
        make="Tesla",
        model="Model S",
        year=2024,
        type="electric",
        sale_type="sale",
        price=78000,
        price_unit="usd",
        fuel_efficiency=120,
        features=["autopilot", "premium interior"],
        horsepower=670,
        seats=5,
    ),
    types.CarInfo(
        make="Tesla",
        model="Model X",
        year=2024,
        type="electric",
        sale_type="both",
        price=220,
        price_unit="usd_per_day",
        fuel_efficiency=102,
        features=["falcon doors", "AWD"],
        horsepower=670,
        seats=6,
    ),
    types.CarInfo(
        make="Rivian",
        model="R1S",
        year=2024,
        type="electric",
        sale_type="sale",
        price=86000,
        price_unit="usd",
        fuel_efficiency=69,
        features=["quad motor", "AWD"],
        horsepower=835,
        seats=7,
    ),
    types.CarInfo(
        make="Rivian",
        model="R1T",
        year=2024,
        type="electric",
        sale_type="sale",
        price=82000,
        price_unit="usd",
        fuel_efficiency=70,
        features=["truck bed", "AWD"],
        horsepower=835,
        seats=5,
    ),
    types.CarInfo(
        make="Lucid",
        model="Air Pure",
        year=2024,
        type="electric",
        sale_type="sale",
        price=69000,
        price_unit="usd",
        fuel_efficiency=131,
        features=["luxury interior", "fast charging"],
        horsepower=480,
        seats=5,
    ),
    types.CarInfo(
        make="Polestar",
        model="2",
        year=2023,
        type="electric",
        sale_type="both",
        price=140,
        price_unit="usd_per_day",
        fuel_efficiency=107,
        features=["Android Automotive", "AWD"],
        horsepower=408,
        seats=5,
    ),
    types.CarInfo(
        make="Volvo",
        model="XC40 Recharge",
        year=2023,
        type="electric",
        sale_type="sale",
        price=54000,
        price_unit="usd",
        fuel_efficiency=92,
        features=["AWD", "premium interior"],
        horsepower=402,
        seats=5,
    ),
    types.CarInfo(
        make="Hyundai",
        model="Ioniq 6",
        year=2024,
        type="electric",
        sale_type="both",
        price=150,
        price_unit="usd_per_day",
        fuel_efficiency=117,
        features=["fast charging", "lane assist"],
        horsepower=225,
        seats=5,
    ),
    types.CarInfo(
        make="Kia",
        model="Niro EV",
        year=2023,
        type="electric",
        sale_type="rental",
        price=100,
        price_unit="usd_per_day",
        fuel_efficiency=113,
        features=["eco mode", "CarPlay"],
        horsepower=201,
        seats=5,
    ),
    types.CarInfo(
        make="Mini",
        model="Cooper SE",
        year=2023,
        type="electric",
        sale_type="rental",
        price=95,
        price_unit="usd_per_day",
        fuel_efficiency=110,
        features=["compact size", "sport mode"],
        horsepower=181,
        seats=4,
    ),
    types.CarInfo(
        make="Nissan",
        model="Leaf",
        year=2023,
        type="electric",
        sale_type="sale",
        price=28000,
        price_unit="usd",
        fuel_efficiency=111,
        features=["CarPlay", "eco mode"],
        horsepower=147,
        seats=5,
    ),
    # Sports (continued)
    types.CarInfo(
        make="Toyota",
        model="Supra",
        year=2024,
        type="sports",
        sale_type="sale",
        price=56000,
        price_unit="usd",
        fuel_efficiency=26,
        features=["turbo", "sport suspension"],
        horsepower=382,
        seats=2,
    ),
    types.CarInfo(
        make="Chevrolet",
        model="Corvette Stingray",
        year=2024,
        type="sports",
        sale_type="sale",
        price=69000,
        price_unit="usd",
        fuel_efficiency=24,
        features=["mid-engine", "performance package"],
        horsepower=490,
        seats=2,
    ),
    types.CarInfo(
        make="Porsche",
        model="911 Carrera",
        year=2023,
        type="sports",
        sale_type="both",
        price=480,
        price_unit="usd_per_day",
        fuel_efficiency=21,
        features=["rear-engine", "sport chrono"],
        horsepower=379,
        seats=4,
    ),
    types.CarInfo(
        make="Ferrari",
        model="F8 Tributo",
        year=2022,
        type="sports",
        sale_type="rental",
        price=1500,
        price_unit="usd_per_day",
        fuel_efficiency=16,
        features=["twin turbo V8", "RWD"],
        horsepower=710,
        seats=2,
    ),
    types.CarInfo(
        make="Lamborghini",
        model="Huracán EVO",
        year=2022,
        type="sports",
        sale_type="rental",
        price=1800,
        price_unit="usd_per_day",
        fuel_efficiency=15,
        features=["V10", "AWD"],
        horsepower=631,
        seats=2,
    ),
    types.CarInfo(
        make="McLaren",
        model="720S",
        year=2022,
        type="sports",
        sale_type="rental",
        price=2000,
        price_unit="usd_per_day",
        fuel_efficiency=18,
        features=["twin turbo V8", "carbon tub"],
        horsepower=710,
        seats=2,
    ),
    types.CarInfo(
        make="Jaguar",
        model="F-Type R",
        year=2023,
        type="sports",
        sale_type="sale",
        price=113000,
        price_unit="usd",
        fuel_efficiency=19,
        features=["supercharged V8", "AWD"],
        horsepower=575,
        seats=2,
    ),
    types.CarInfo(
        make="Aston Martin",
        model="Vantage",
        year=2023,
        type="sports",
        sale_type="rental",
        price=950,
        price_unit="usd_per_day",
        fuel_efficiency=20,
        features=["twin turbo V8", "luxury interior"],
        horsepower=503,
        seats=2,
    ),
    types.CarInfo(
        make="BMW",
        model="M4",
        year=2024,
        type="sports",
        sale_type="sale",
        price=78000,
        price_unit="usd",
        fuel_efficiency=20,
        features=["M package", "RWD"],
        horsepower=473,
        seats=4,
    ),
    types.CarInfo(
        make="Mercedes",
        model="AMG GT",
        year=2023,
        type="sports",
        sale_type="sale",
        price=125000,
        price_unit="usd",
        fuel_efficiency=19,
        features=["twin turbo V8", "track mode"],
        horsepower=523,
        seats=2,
    ),
    # Vans (continued)
    types.CarInfo(
        make="Ford",
        model="Transit",
        year=2023,
        type="van",
        sale_type="rental",
        price=110,
        price_unit="usd_per_day",
        fuel_efficiency=18,
        features=["cargo capacity", "high roof"],
        horsepower=310,
        seats=2,
    ),
    types.CarInfo(
        make="Ram",
        model="ProMaster",
        year=2023,
        type="van",
        sale_type="sale",
        price=42000,
        price_unit="usd",
        fuel_efficiency=18,
        features=["cargo space", "rear camera"],
        horsepower=276,
        seats=2,
    ),
    types.CarInfo(
        make="Nissan",
        model="NV3500",
        year=2022,
        type="van",
        sale_type="sale",
        price=39000,
        price_unit="usd",
        fuel_efficiency=17,
        features=["tow package"],
        horsepower=375,
        seats=12,
    ),
    types.CarInfo(
        make="Chevrolet",
        model="Express",
        year=2022,
        type="van",
        sale_type="rental",
        price=115,
        price_unit="usd_per_day",
        fuel_efficiency=16,
        features=["cargo space"],
        horsepower=276,
        seats=2,
    ),
    types.CarInfo(
        make="Mercedes",
        model="Sprinter",
        year=2023,
        type="van",
        sale_type="both",
        price=150,
        price_unit="usd_per_day",
        fuel_efficiency=20,
        features=["high roof", "AWD"],
        horsepower=188,
        seats=12,
    ),
    # Hatchbacks
    types.CarInfo(
        make="Volkswagen",
        model="Golf",
        year=2023,
        type="hatchback",
        sale_type="rental",
        price=60,
        price_unit="usd_per_day",
        fuel_efficiency=33,
        features=["CarPlay", "manual option"],
        horsepower=147,
        seats=5,
    ),
    types.CarInfo(
        make="Honda",
        model="Civic Hatchback",
        year=2023,
        type="hatchback",
        sale_type="both",
        price=65,
        price_unit="usd_per_day",
        fuel_efficiency=34,
        features=["sport mode", "AC"],
        horsepower=180,
        seats=5,
    ),
    types.CarInfo(
        make="Hyundai",
        model="Veloster",
        year=2022,
        type="hatchback",
        sale_type="sale",
        price=23000,
        price_unit="usd",
        fuel_efficiency=30,
        features=["3-door layout", "sport package"],
        horsepower=201,
        seats=4,
    ),
    types.CarInfo(
        make="Kia",
        model="Soul",
        year=2023,
        type="hatchback",
        sale_type="rental",
        price=55,
        price_unit="usd_per_day",
        fuel_efficiency=31,
        features=["AC", "Bluetooth"],
        horsepower=147,
        seats=5,
    ),
    types.CarInfo(
        make="Toyota",
        model="Corolla Hatchback",
        year=2023,
        type="hatchback",
        sale_type="both",
        price=62,
        price_unit="usd_per_day",
        fuel_efficiency=33,
        features=["Apple CarPlay", "lane assist"],
        horsepower=169,
        seats=5,
    ),
    # Coupes
    types.CarInfo(
        make="Honda",
        model="Civic Coupe",
        year=2020,
        type="coupe",
        sale_type="sale",
        price=21000,
        price_unit="usd",
        fuel_efficiency=32,
        features=["Bluetooth", "AC"],
        horsepower=158,
        seats=4,
    ),
    types.CarInfo(
        make="BMW",
        model="430i Coupe",
        year=2023,
        type="coupe",
        sale_type="sale",
        price=49000,
        price_unit="usd",
        fuel_efficiency=27,
        features=["M sport", "premium interior"],
        horsepower=255,
        seats=4,
    ),
    types.CarInfo(
        make="Audi",
        model="A5 Coupe",
        year=2023,
        type="coupe",
        sale_type="both",
        price=160,
        price_unit="usd_per_day",
        fuel_efficiency=26,
        features=["quattro", "luxury interior"],
        horsepower=261,
        seats=4,
    ),
    types.CarInfo(
        make="Mercedes",
        model="CLA250 Coupe",
        year=2023,
        type="coupe",
        sale_type="rental",
        price=150,
        price_unit="usd_per_day",
        fuel_efficiency=28,
        features=["turbo", "premium sound"],
        horsepower=221,
        seats=4,
    ),
    types.CarInfo(
        make="Toyota",
        model="86",
        year=2022,
        type="coupe",
        sale_type="sale",
        price=28000,
        price_unit="usd",
        fuel_efficiency=24,
        features=["RWD", "manual option"],
        horsepower=205,
        seats=4,
    ),
    # Wagons
    types.CarInfo(
        make="Subaru",
        model="Outback",
        year=2023,
        type="wagon",
        sale_type="both",
        price=78,
        price_unit="usd_per_day",
        fuel_efficiency=29,
        features=["AWD", "roof rails"],
        horsepower=182,
        seats=5,
    ),
    types.CarInfo(
        make="Volvo",
        model="V60",
        year=2023,
        type="wagon",
        sale_type="sale",
        price=51000,
        price_unit="usd",
        fuel_efficiency=25,
        features=["luxury interior", "safety suite"],
        horsepower=250,
        seats=5,
    ),
    types.CarInfo(
        make="Audi",
        model="A4 Allroad",
        year=2023,
        type="wagon",
        sale_type="rental",
        price=145,
        price_unit="usd_per_day",
        fuel_efficiency=26,
        features=["quattro", "lifted suspension"],
        horsepower=261,
        seats=5,
    ),
    types.CarInfo(
        make="Mercedes",
        model="E450 All-Terrain",
        year=2023,
        type="wagon",
        sale_type="sale",
        price=72000,
        price_unit="usd",
        fuel_efficiency=24,
        features=["AWD", "air suspension"],
        horsepower=362,
        seats=5,
    ),
    types.CarInfo(
        make="Volkswagen",
        model="Golf SportWagen",
        year=2022,
        type="wagon",
        sale_type="sale",
        price=32000,
        price_unit="usd",
        fuel_efficiency=31,
        features=["CarPlay", "roof rails"],
        horsepower=170,
        seats=5,
    ),
]
