# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions


class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractQuestions(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List[str]:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractQuestions", llm_response=llm_response, mode="request"
        )
        return typing.cast(typing.List[str], result)

    def ExtractRenterProfile(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CallerProfile:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractRenterProfile",
            llm_response=llm_response,
            mode="request",
        )
        return typing.cast(types.CallerProfile, result)

    def ExtractResume(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractResume", llm_response=llm_response, mode="request"
        )
        return typing.cast(types.Resume, result)


class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractQuestions(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List[str]:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractQuestions", llm_response=llm_response, mode="stream"
        )
        return typing.cast(typing.List[str], result)

    def ExtractRenterProfile(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.CallerProfile:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractRenterProfile",
            llm_response=llm_response,
            mode="stream",
        )
        return typing.cast(stream_types.CallerProfile, result)

    def ExtractResume(
        self,
        llm_response: str,
        baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(
            function_name="ExtractResume", llm_response=llm_response, mode="stream"
        )
        return typing.cast(stream_types.Resume, result)
