# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel


StreamStateValueT = typing.TypeVar("StreamStateValueT")


class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]


# #########################################################################
# Generated classes (4)
# #########################################################################


class CallerData(BaseModel):
    profile: typing.Optional["CallerProfile"] = None
    questions: typing.List[str]


class CallerProfile(BaseModel):
    name: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    email: typing.Optional[str] = None
    rental_dates: typing.Optional[str] = None
    car_preferences: typing.List[str]
    budget_low: typing.Optional[float] = None
    budget_high: typing.Optional[float] = None
    location: typing.Optional[str] = None
    additional_notes: typing.List[str]
    intent: typing.Optional[typing.Union[str, str, str, str]] = None


class CarInfo(BaseModel):
    make: typing.Optional[str] = None
    model: typing.Optional[str] = None
    year: typing.Optional[int] = None
    type: typing.Optional[
        typing.Union[str, str, str, str, str, str, str, str, str, str, str, str]
    ] = None
    sale_type: typing.Optional[typing.Union[str, str, str]] = None
    price: typing.Optional[int] = None
    price_unit: typing.Optional[typing.Union[str, str]] = None
    fuel_efficiency: typing.Optional[int] = None
    features: typing.List[str]
    horsepower: typing.Optional[int] = None
    seats: typing.Optional[int] = None


class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]


# #########################################################################
# Generated type aliases (3)
# #########################################################################


CarType: typing_extensions.TypeAlias = typing.Optional[
    typing.Union[str, str, str, str, str, str, str, str, str, str, str, str]
]


PriceUnit: typing_extensions.TypeAlias = typing.Optional[typing.Union[str, str]]


SaleType: typing_extensions.TypeAlias = typing.Optional[typing.Union[str, str, str]]
