# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {
    "types.CallerData": types.CallerData,
    "stream_types.CallerData": stream_types.CallerData,
    "types.CallerProfile": types.CallerProfile,
    "stream_types.CallerProfile": stream_types.CallerProfile,
    "types.CarInfo": types.CarInfo,
    "stream_types.CarInfo": stream_types.CarInfo,
    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,
}
