# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from pydantic import BaseModel



CheckT = typing_extensions.TypeVar("CheckT")
CheckName = typing_extensions.TypeVar("CheckName", bound=str)


class Check(BaseModel):
    name: str
    expression: str
    status: str


class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]


def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())


def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))


# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (4)
# #########################################################################


class CallerData(BaseModel):
    profile: "CallerProfile"
    questions: typing.List[str]


class CallerProfile(BaseModel):
    name: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    email: typing.Optional[str] = None
    rental_dates: typing.Optional[str] = None
    car_preferences: typing.List[str]
    budget_low: typing.Optional[float] = None
    budget_high: typing.Optional[float] = None
    location: typing.Optional[str] = None
    additional_notes: typing.List[str]
    intent: typing.Optional[
        typing.Union[
            typing_extensions.Literal["buying"],
            typing_extensions.Literal["renting"],
            typing_extensions.Literal["inquiry"],
            typing_extensions.Literal["other"],
        ]
    ] = None


class CarInfo(BaseModel):
    make: str
    model: str
    year: int
    type: typing.Union[
        typing_extensions.Literal["sedan"],
        typing_extensions.Literal["suv"],
        typing_extensions.Literal["truck"],
        typing_extensions.Literal["van"],
        typing_extensions.Literal["coupe"],
        typing_extensions.Literal["convertible"],
        typing_extensions.Literal["hatchback"],
        typing_extensions.Literal["wagon"],
        typing_extensions.Literal["sports"],
        typing_extensions.Literal["electric"],
        typing_extensions.Literal["luxury"],
        typing_extensions.Literal["other"],
    ]
    sale_type: typing.Union[
        typing_extensions.Literal["rental"],
        typing_extensions.Literal["sale"],
        typing_extensions.Literal["both"],
    ]
    price: int
    price_unit: typing.Union[
        typing_extensions.Literal["usd_per_day"], typing_extensions.Literal["usd"]
    ]
    fuel_efficiency: int
    features: typing.List[str]
    horsepower: int
    seats: int


class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]


# #########################################################################
# Generated type aliases (3)
# #########################################################################


CarType: typing_extensions.TypeAlias = typing.Union[
    typing_extensions.Literal["sedan"],
    typing_extensions.Literal["suv"],
    typing_extensions.Literal["truck"],
    typing_extensions.Literal["van"],
    typing_extensions.Literal["coupe"],
    typing_extensions.Literal["convertible"],
    typing_extensions.Literal["hatchback"],
    typing_extensions.Literal["wagon"],
    typing_extensions.Literal["sports"],
    typing_extensions.Literal["electric"],
    typing_extensions.Literal["luxury"],
    typing_extensions.Literal["other"],
]


PriceUnit: typing_extensions.TypeAlias = typing.Union[
    typing_extensions.Literal["usd_per_day"], typing_extensions.Literal["usd"]
]


SaleType: typing_extensions.TypeAlias = typing.Union[
    typing_extensions.Literal["rental"],
    typing_extensions.Literal["sale"],
    typing_extensions.Literal["both"],
]
